TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += b17tmag.db
DB += b17tmag_error_setter.db
DATA += b17tmag.proto

#=======================================
include $(TOP)/configure/RULES
