TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += b17tmag.db
DATA += b17tmag.proto

#=======================================
include $(TOP)/configure/RULES
